'use client';
import { FormEvent, useEffect, useState } from 'react';

export default function Account() {
  const [mode,setMode]=useState<'login'|'register'>('login'); const [user,setUser]=useState<any>(null); const [orders,setOrders]=useState<any[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){ const a=await fetch('/api/auth'); const ad=await a.json(); setUser(ad.user||null); if(ad.user){const r=await fetch('/api/orders');const d=await r.json();if(r.ok)setOrders(d.orders||[]);}}
  useEffect(()=>{load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,...data})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'Something went wrong.');return;}setUser(d.user);e.currentTarget.reset();const rr=await fetch('/api/orders');const od=await rr.json();if(rr.ok)setOrders(od.orders||[]);}
  async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setUser(null);setOrders([]);}
  if(user)return <main className="wrap section"><div className="eyebrow">Account</div><div className="account-head"><div><h1>Welcome, {user.name}</h1><p className="muted">{user.email} · {user.role}</p></div><button className="btn" onClick={logout}>Sign out</button></div><section className="section"><div className="eyebrow">Your orders</div><h2>Order history</h2>{orders.length===0?<div className="notice">No orders yet. <a href="/shop"><u>Browse the shop</u></a>.</div>:<div className="order-list">{orders.map(o=><article className="card customer-order" key={o.id}><div className="order-head"><div><strong>{o.id}</strong><div className="muted">{new Date(o.createdAt).toLocaleString('en-IN')}</div></div><div><span className="status-live">{o.status}</span> <span className="status-hidden">{o.paymentStatus}</span></div></div><div className="order-lines">{(o.items||[]).map((i:any,idx:number)=><div key={idx}>{i.name} · {i.size} · {i.color} × {i.qty}</div>)}</div><div className="order-footer"><strong>₹{o.amount}</strong><span>{o.paymentMethod}</span>{o.shipment?.courier&&<span>{o.shipment.courier}{o.shipment.awb?` · ${o.shipment.awb}`:''}</span>}{o.shipment?.trackingUrl&&<a className="btn" href={o.shipment.trackingUrl} target="_blank">Track shipment</a>}</div>{(o.statusHistory||[]).length>0&&<div className="timeline">{(o.statusHistory||[]).map((h:any,i:number)=><div className="timeline-item" key={i}><b>{h.status}</b><span>{new Date(h.at).toLocaleString('en-IN')}</span>{h.note&&<small>{h.note}</small>}</div>)}</div>}</article>)}</div>}</section></main>;
  return <main className="wrap section"><div className="eyebrow">10 &amp; Half</div><h1>{mode==='login'?'Sign in':'Create account'}</h1><form className="form" onSubmit={submit}>{mode==='register'&&<label className="field">Name<input name="name" minLength={2} required/></label>}{mode==='register'&&<label className="field">Phone<input name="phone" inputMode="tel"/></label>}<label className="field">Email<input name="email" type="email" required/></label><label className="field">Password<input name="password" type="password" minLength={8} required/></label>{error&&<p className="notice error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="btn ghost" style={{marginTop:12}} onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create a new account':'Already have an account? Sign in'}</button></main>;
}
